#PBS -N rotate_batch
#PBS -l walltime=96:00:00
#PBS -l select=1:ncpus=1
#PBS -j oe
#PBS -m bea
#PBS -S /bin/bash
#PBS -r n
#PBS -M paul.gierz@awi.de

##### BEGIN USER INTERFACE
#
Exp_ID='RCP4m'   
Data_source='/csys/nobackup1_PALEO/pgierz/Data_Raw/mpiom/Clim/aor/RCP4m/RCP4.5m-s_mpiom_3400-3499_Clim.nc'
#   P. Gierz, 14.10.2013
##### END USER INTERFACE
cd /uv/user/pgierz/tracers_1p2/expt/scripts

source /uv/user/pgierz/tracers_1p2/expt/scripts/new_run.sh $Exp_ID

#check that the raw inputs folder is empty by moving everything to the backups.
mv -f /uv/user/pgierz/tracers_1p2/expt/raw_inputs/* /uv/user/pgierz/tracers_1p2/expt/raw_inputs_backups/

#link to raw data and split files
ln -s $Data_source /uv/user/pgierz/tracers_1p2/expt/raw_inputs/data_raw
cdo -f nc -t mpiom1 -splitsel,30 -selcode,3,4,7 /uv/user/pgierz/tracers_1p2/expt/raw_inputs/data_raw /uv/user/pgierz/tracers_1p2/expt/raw_inputs/${Exp_ID}_velocity_

# Make the WORKLIST file
for f in /uv/user/pgierz/tracers_1p2/expt/raw_inputs/*nc;
do 
    basename ${f%.*} >> /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST;
done
lastfile='XXXX'    #define first lastfile by hand

#get length of WORKLIST to see how often to run matlab batch
redo=`sed -n '$=' /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST`


# Main loop
for i in $(seq 1 $redo);
do
    #echo $i;
    file=`head -1 /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST`
    sed "s/${lastfile}/${file}/g" /uv/user/pgierz/tracers_1p2/expt/scripts/rotate_template.m > /uv/user/pgierz/tracers_1p2/expt/scripts/rotate_uv_timesteps.m # changes the file in the matlab scripts
    cp /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST_template
    rm /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST
    sed -e '1d' /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST_template > /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST
    rm /uv/user/pgierz/tracers_1p2/expt/raw_inputs/WORKLIST_template
    matlab -nodisplay -r "run('/uv/user/pgierz/tracers_1p2/expt/scripts/rotate_uv_timesteps.m');"
    wait
done

# when everything is done, consider doing a cdo cat and doing python make_inputs.py to make nest links.

cdo cat /uv/user/pgierz/tracers_1p2/expt/raw_inputs/*normalgrid_r360x180_final.nc /uv/user/pgierz/tracers_1p2/expt/finished_inputs/${Exp_ID}_finished.nc
rm -f /uv/user/pgierz/tracers_1p2/expt/raw_inputs/*normalgrid_r360x180_final.nc # remove temporary files to save disk space...

# make links
ln -s /uv/user/pgierz/tracers_1p2/expt/finished_inputs/${Exp_ID}_finished.nc /uv/user/pgierz/tracers_1p2/expt/expt_${Exp_ID}/nests/data_raw
ln -s /uv/user/pgierz/tracers_1p2/expt/scripts/make_dates.py /uv/user/pgierz/tracers_1p2/expt/expt_${Exp_ID}/nests
cd /uv/user/pgierz/tracers_1p2/expt/expt_${Exp_ID}/nests/
python make_dates.py

if run_cms;
then
    mpirun -np 1 ./cms ${Exp_ID}
fi

echo "Done!"
